### ISSUE TITLE
[FEAT] B2B 화면에서 주문 리스트 조회

### ISSUE THREAD

**Issue by worldcenter96** [impostor-commerce/impostor-commerce-backend#11]
### 담당자
- 박가온누리

## 기능 이름
- B2B 화면에서 주문 리스트 조회

## 기능 내용
- 판매자의 모든 주문 확인 및 주문, 배송 상태를 조회합니다.

예외 처리
- [OrderException] : 무슨 무슨 작업을 하면 OrderException이 발생한다.

<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">N/A</pre></td>
        <td><pre lang="json">[
  {
    "name": "핸드크림",
    "trackingNumber": "12314324234234!",
    "orderStatus": "CONFIRMED",
    "deliveryStatus": "NOT_SHIPPED",
    "totalPrice": 54000,
    "quantity": 3,
    "createdAt": "1111-11-11 14:00:00",
    "modifiedAt": "1111-11-11 14:00:00"
  },
  {
    "name": "핸드크림",
    "trackingNumber": "12314324234234!",
    "orderStatus": "CONFIRMED",
    "deliveryStatus": "NOT_SHIPPED",
    "totalPrice": 54000,
    "quantity": 3,
    "createdAt": "1111-11-11 14:00:00",
    "modifiedAt": "1111-11-11 14:00:00"
  },
  {
    "name": "핸드크림",
    "trackingNumber": "12314324234234!",
    "orderStatus": "CONFIRMED",
    "deliveryStatus": "NOT_SHIPPED",
    "totalPrice": 54000,
    "quantity": 3,
    "createdAt": "1111-11-11 14:00:00",
    "modifiedAt": "1111-11-11 14:00:00"
  },
  "totalPages": 2985,
  "totalElements": 29844
]</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
다른 페이지네이션과 동일한 응답형태로 맞춰졌으면 좋겠습니다

**Comment by loadkrnis** [comment]
json 문법오류 ..

**Comment by worldcenter96** [comment]
이미 main에 머지됨
