### ISSUE TITLE
[FEAT] B2B 주문의 배송 상태 변경

### ISSUE THREAD

**Issue by worldcenter96** [impostor-commerce/impostor-commerce-backend#12]
### 담당자
- 박가온누리

## 기능 이름
- B2B 주문의 배송 상태 변경

## 기능 내용
- 주문에 운송장 등록 시 주문 상태가 NOT_SHIPPED에서 IN_TRANSIT로 변경 됩니다.
- 12자리 운송번호만 입력 가능합니다.

예외 처리
- [OrderException] : 무슨 무슨 작업을 하면 OrderException이 발생한다.

<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">{
    "trackingNumber": "123456789012"
}</pre></td>
        <td><pre lang="json">{
    "id": 2,
    "name": "손선풍기",
    "trackingNumber": "123456789012",
    "orderStatus": "CONFIRMED",
    "deliveryStatus": "IN_TRANSIT",
    "totalPrice": 10000,
    "quantity": 2,
    "memberName": "John Doe",
    "productName": "손선풍기",
    "createdAt": "2024-12-05T23:23:27",
    "modifiedAt": "2024-12-06T13:33:04.985627"
}</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
URL패턴 deliverystatus -> delivery-status
