### ISSUE TITLE
[FEAT] B2B 판매자 등록 요청 승인 및 거절

### ISSUE THREAD

**Issue by bbobsang** [impostor-commerce/impostor-commerce-backend#15]
### $\bf{\normalsize{\color{RED}PATCH}}$ `/api/admin/b2b/{memberId}/approve`

<br>

### 담당자
- 박지예
<br>

## 기능 이름
- B2B 등록 요청 승인 및 거절

## 기능 내용
-  판매자 권한에 대한 요청 승인 및 거절

## 예외 처리
- [RuntimeException] : 잘못된 값으로 요청 시 RuntimeException이 발생.

<br><br>
<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json"> // 승인 시
 {
  "status": "ACTIVE"
} 
<br>

</pre></td>
        <td><pre lang="json"> // 승인 시
{
  "id": 1234,
  "email": "example@domain.com",
  "name": "존 도",
  "activeStatus": "ACTIVE",
  "createdAt": "2024-12-06T00:00:00",
  "modifiedAt": "2024-12-06T00:00:00"
}
<br>

</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
Response Body는 수정이 끝난 엔티티
