### ISSUE TITLE
[FEAT] B2B 특정 상품 조회

### ISSUE THREAD

**Issue by gabeen-dev** [impostor-commerce/impostor-commerce-backend#16]
### 담당자
- 김가빈

## 기능 이름
- B2B 특정 상품 조회

## 기능 내용
- PostRequestDto 요청 시 등록한 상품의 이름, 내용, 수량, 가격 등 상품 상태 조회 할 수있다.
  - 단, 로그인한 사용자의 본인 상품만 조회. 
  - 상품의 이미지를 함꼐 볼 수 있다.

예외 처리
- [RuntimeException] : 잘못된 값으로 요청 시 RuntimeException이 발생한다.

<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">N/A</pre></td>
        <td><pre lang="json">{
 "id" : 1,
 "name" : "상품이름",
 "description" : "상품내용",
 "stockQuantity" : "10",
 "price" : "10000",
 "status" : "PENDING", //ON_SALE(판매중), OFF_SALE(판매종료)
 "category" : "none",//추후 추가 예정
 "subCategory" : "none",//추후 추가 예정
 "contents": [
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"}	  
 ... ] 
}</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
B2B모듈에서 개발예정

{
 "id" : 1,
 "name" : "상품이름",
 "description" : "상품내용",
 "stockQuantity" : "10",
 "price" : "10000",
 "status" : "PENDING", //ON_SALE(판매중), OFF_SALE(판매종료)
 "category" : "none",//추후 추가 예정
 "subCategory" : "none",//추후 추가 예정
 "buyers": [ // 모든 구매자
    { "name": "박민규" }, { "name": "박민규2" }, { "name": "박민규3" }
  ]
 "contents": [
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"}	  
 ... ] 
}
