### ISSUE TITLE
[FEAT] B2C 상품 검색

### ISSUE THREAD

**Issue by hwk9407** [impostor-commerce/impostor-commerce-backend#17]
### 담당자
- 허원경

## 기능 이름
- B2C 검색 키워드를 이용한 상품 검색

## 기능 내용
- B2C 사용자가 키워드로 해당 상품이 있는지 검색하는 API
- 요청 시 쿼리 파라미터로 값 전달
- `전달 가능한 값` (미입력 시 기본값 *)
  - page 기본값: 1
  - size 기본값: 10
  - orderBy: `*ASC` `DESC`
  - sortBy: `*name` `price` `createdAt`
  - category: `*DEFAULT` `TOP` `BOTTOM` `OUTERWEAR` `ACCESSORIES` `FOOTWEAR`
  - subCategory: `*DEFAULT` `T_SHIRT` `SHIRT` `KNIT` `JEANS` `SLACKS` `SHORTS` `COATS` `JACKETS` `PARKAS` `CARDIGANS` `HAT` `BELT` `GLOVES` `SNEAKERS` `BOOTS` `DRESS_SHOES`
- 기본값
  - keyword 필수입력 null불가
  - orderBy 기본값: asc
  - sortBy 기본값: name
  - category 기본값: DEFAULT
  - subCategory 기본값: DEFAULT
- `category`, `subCategory`를 통하여 카테고리를 선택적으로 추가 필터링
  - `category`와  `subCategory`의 enum클래스를 아직 정의 하지 않았으므로, 정의되어 있지 않은 카테고리로 요청하지 못하도록 설정해야 함
- `keyword`를 제외하고 동적 쿼리를 적용하여 모든 쿼리 파라미터를 인자로 전달하지 않아도 작동되도록 구성
- 상품 상태가 `OFF_SALE`, `PENDING` 는 검색되지 않도록 설정해야 함

예외 처리
- [IllegalArgumentException] : 키워드없이(빈문자열 포함) 요청하면 400 에러 발생
- [IllegalArgumentException] : size를 50보다 크게 설정할 경우 400 에러 발생
- [IllegalArgumentException] : page를 1보다 작게 설정할 경우 400 에러 발생
- [IllegalArgumentException] : 그 외 `전달 가능한 값`이 아닌 값을 전달 할 경우 400 에러 발생(대소문자 구별)

</body>
</html>

<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    N/A
    <tr>
        <td><pre lang="json"></pre></td>
        <td><pre lang="json">{
  "content": [
    {
      "id": 1,
      "name": "상품 이름",
      "description": "상품 내용",
      "stockQuantity": "상품 수량",
      "price": 10000,
      "status": "ON_SALE",
      "category": "TOP",
      "subCategory": "T_SHIRT",
      "createdAt": "2024-12-04 00:00:00",
      "modifiedAt": "2024-12-04 00:00:00"
    },
    {
      ...
    }
  ]
  "page": 1,
  "size": 10,
  "totalPage": 5
}</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
- 응답 값이 페이지네이션 형태로 변경이 필요함
