### ISSUE TITLE
[FEAT] B2C 단건 주문 조회 기능 구현

### ISSUE THREAD

**Issue by matino0216** [impostor-commerce/impostor-commerce-backend#24]
### 담당자
- 이시우

## 기능 이름
- B2C 단건 주문 조회

## 기능 내용
- 단건 주문의 내용을 상세히 조회한다.

예외 처리
- [RuntimeException] : 잘못된 값으로 요청하면 RuntimeException이 발생한다.

<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">
N/A
</pre></td>
        <td><pre lang="json">{
  "id" : 1,
  "name" : "상품 이름",
  "quantity" : 3,
  "totalPrice" : 54000,
  "orderStatus" : "CONFIRMED",
  "deliveryStatus": "IN_TRANSIT",
  "createdAt" : "2024-12-04T00:00:00",
  "modifiedAt" : "2024-12-05T00:00:00"
}</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
`orderId` -> `id` 필드명 변경
