### ISSUE TITLE
[FEAT] B2C 회원 조회

### ISSUE THREAD

**Issue by bbobsang** [impostor-commerce/impostor-commerce-backend#7]
### $\bf{\normalsize{\color{RED}GET}}$ /api/admin/b2c-members

<br>

### 담당자
- 박지예
<br>

## 기능 이름
- B2C 회원 조회

## 기능 내용
- 판매자가 아닌 B2C (일반 회원)의 리스트를 조회.
- 관리자는 비활성화 계정도 확인할 수 있어야함.
{ GET /api/b2c-members?status=INACTIVE (비활성화 사용자 리스트 조회 id (PK) ) }

- B2C 회원 조회를 통해서 수행 할 수 있는 ADMIN만의 기능이 있을 것이기 때문에 필요함. 

## 예외 처리
- [RuntimeException] : B2C가 아닌 회원을 조회 요청하거나 잘못된 값으로 요청 시 RuntimeException이 발생.

<br><br>
<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">
N/A
</pre></td>
        <td><pre lang="json">{
  "contents": [
    {
      "id": 1,
      "email": "user1@example.com",
      "name": "존도",
      "status": "ACTIVE",
    },
    {
      "id": 2,
      "email": "user2@example.com",
      "name": "길동홍",
      "status": "INACTIVE",

    }
  ]
  "page": 1,
  "size": 10,
  "sortBy": "name",
  "orderBy": "desc",
  "totalpage": 5
}</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
- 페이지네이션 적용
 - /customer-member 엔드포인트 변경해야하는데 이 API 꼭 필요한지? 논의필요
