### ISSUE TITLE
[FEAT] B2B 상품 등록

### ISSUE THREAD

**Issue by gabeen-dev** [impostor-commerce/impostor-commerce-backend#8]
### 담당자
- 김가빈

## 기능 이름
- 판매자 상품 등록

## 기능 내용
- PostRequest 요청 시 상품을 등록 한다.
  - 승인된 B2B멤버만 등록 할 수 있다.
- 등록내용
  - 상품이름
  - 상품내용
  - 상품수량
  - 상품가격
  - 상품상태 : PENDING(판매대기) ON_SALE(판매중), OFF_SALE(판매종료)
    - 기본값 : PENDING
  - 카테고리 : none //추후 추가 예정
    - 기본값 : none 
  - 하위카테고리 : none //추후 추가 예정
    - 기본값 : none 
   - 이미지
     - 이미지는 리스트 형식으로 받는다.
     - 이미지는 최소 1개를 초과하여 받는다.

예외 처리
- [RuntimeException] : 판매자 권한이 없으면 RuntimeException이 발생한다.
- [RuntimeException] : 입력값이 없으면 RuntimeException이 발생한다.

<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">{
 "name": "상품이름",
 "description": "상품내용",
 "stockQuantity": 10,
 "price": 10000,
 "category": "none",//추후 추가 예정
 "subCategory": "none",//추후 추가 예정
 "images": [
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"}	  
 ... ] 
}</pre></td>
        <td><pre lang="json">{
 "id": 1,
 "name": "상품이름",
 "description": "상품내용",
 "stockQuantity": 10,
 "price": 10000,
 "status": "PENDING", //ON_SALE(판매중), OFF_SALE(판매종료)
 "category": "none",//추후 추가 예정
 "subCategory": "none",//추후 추가 예정
 "images": [
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"}	  
 ... ] 
}</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
```json
{
 "name": "상품이름", -> string
 "description" : "상품내용",
 "stockQuantity": 10, -> number
 "price" : "10000",
 "status" : "PENDING", //ON_SALE(판매중), OFF_SALE(판매종료)
 "category" : "none",//추후 추가 예정
 "subCategory" : "none",//추후 추가 예정
 "contents": [
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"},
     {"url" : "http://example.com/api/upload"}	  
 ... ] 
}
```

**Comment by loadkrnis** [comment]
TEST

**Comment by loadkrnis** [comment]
T2222222222222EST

**Comment by loadkrnis** [comment]
- contents -> thumbnails or images
 
```json
 "images": [
     {"url" : "http://example.com/api/upload" },
     {"url" : "http://example.com/api/upload", "originalFileName": "ddddd.jpg" },
     {"url" : "http://example.com/api/upload"}	  
  ]

 "images": [ 
    "http://example.com/api/upload", 
    "http://example.com/api/upload", 
    "http://example.com/api/upload"
  ]
```
