### ISSUE TITLE
[FEAT] Admin사용자 전용 B2B 회원 조회

### ISSUE THREAD

**Issue by bbobsang** [impostor-commerce/impostor-commerce-backend#9]
### $\bf{\normalsize{\color{RED}GET}}$ 특정 status에 해당하는 B2B 회원 조회 `”b2b-members/status/{status}”`
<br>

### 담당자
- 박지예
<br>

## 기능 이름
- B2B 회원 조회 

## 기능 내용
- Admin 사용자 전용 API
- 일반회원이 아닌 B2B(판매자) 유저의 리스트를 조회.
- status: PENDING, INACTIVE, ACTIVE

## 예외 처리
- [RuntimeException] : B2B가 아닌 회원을 조회 요청하거나 잘못된 값으로 요청 시 RuntimeException이 발생.

<br><br>
<table>
    <tr>
        <th>Requqest Body</th>
        <th>Response Body</th>
    </tr>
    <tr>
        <td><pre lang="json">
N/A
</pre></td>
        <td><pre lang="json">{
  "members": [
    {
      "id": 1,
      "email": "b2buser1@example.com",
      "name": "제인도",
      "status": "ACTIVE",

    },
    {
      "id": 2,
      "email": "b2buser2@example.com",
      "name": "베이비도",
      "status": "INACTIVE",
    }
  ]
}
</pre></td>
    </tr>
</table>

**Comment by loadkrnis** [comment]
admin사용자 전용 API라고 명시하면 좋을 것 같아요

**Comment by loadkrnis** [comment]
GET `/api/b2b-members?status=INACTIVE` => 미승인 사용자 리스트 조회 id(PK)

PUT `/api/b2b-members/{b2bMemberId}/status` { "status": "ACTIVE" }
